### ISSUE TITLE
Performance on scene with complex geometry

### ISSUE THREAD

**Issue by Moreland-cas** [dluvizon/scene-aware-3d-multi-human#11]
Hi, great work!
I noticed that most of the demos are shown on a flat plane, Have you tested the reconstructed precision on scene with complex geometry? (like boxes, slope terrains, etc.)

**Comment by dluvizon** [comment]
Hi,
there is no specific prior in the method about a flat ground. But since the camera is static, any parts of the floor that are not visible (like behind a box or a slop) will not be modeled. Apart from that, the quality of the scene recontruction also strongly depends on the quality of the estimated depth.

**Comment by Moreland-cas** [comment]
> Hi, there is no specific prior in the method about a flat ground. But since the camera is static, any parts of the floor that are not visible (like behind a box or a slop) will not be modeled. Apart from that, the quality of the scene recontruction also strongly depends on the quality of the estimated depth.

Thanks for the quick reply!
